#spring:
#  profiles:
#    active: dev
#
##公共配置与profiles选择无关
#mybatis:
#  typeAliasesPackage: com.xdd.entity
#  mapperLocations: classpath:mybatis/*.xml
#
##开发配置
#spring:
#  profiles: dev
#
#   datasource:
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#
#

server:
  port: 8090

spring:
  application:
    name: dev-service
  profiles:
    active: dev #默认环境(开发环境
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
        username: root
        password: 1996
        driver-class-name: com.mysql.jdbc.Driver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:/mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity.model  # 注意：对应实体类的路径
